// legacy/src/components/layouts/Header.vue
<template>
  <header
    class="header h-header-height p-0 m-0 flex-center flex-wrap inset-0 w-full z-header"
    :class="{
      'sticky background shadow-lg transition-all duration-500 ease-in-out': !isHomePage,
      fixed: isHomePage,
      'surface transition-none': isHomePage && isLoading,
      'text-gray-200 bg-transparent': isHomePage && !isLoading,
      'header--is-scrolled bg-theme-tone shadow-lg transition-all duration-500 ease-in-out':
        isHomePage && isScrolled
    }"
  >
    <div
      class="container px-4 sm:px-6 lg:px-8 mx-auto flex justify-between items-center h-full"
    >
      <div class="header__left flex items-center h-full">
        <Logo />
      </div>
      <div class="header__right flex items-center h-full">
        <Navigation v-if="!isHomePage" />
        <ToggleTheme class="ml-4" />
      </div>
    </div>
    <Indicator v-if="isPostPage" />
  </header>
</template>

<script>
import loadMixin from "~/vue-utils/mixins/load";
import pageMixin from "~/vue-utils/mixins/page";
import routerMixin from "~/vue-utils/mixins/router";

import Logo from "./header/Logo";
import ToggleTheme from "./header/ToggleTheme";
import Navigation from "./header/Navigation";
import Indicator from "./header/Indicator";

export default {
  components: {
    Logo,
    ToggleTheme,
    Navigation,
    Indicator
  },

  mixins: [pageMixin, routerMixin, loadMixin],

  props: {
    isScrolled: {
      type: Boolean,
      default: false
    }
  }
};
</script>

<style lang="scss" scoped>
// Styles
</style>

// src/components/layout/Header.tsx
"use client";

import classNames from "classnames";
import { useAtomValue } from "jotai";
import ThemeToggle from "@/components/theme/ThemeToggle";
import { scrolledStore } from "@/store/theme";

const Header = ({ className, ...props }: React.ComponentProps<"header">) => {
  const { isScrolled } = useAtomValue(scrolledStore);

  return (
    <header
      {...props}
      className={classNames(
        "flex-center fixed inset-0 z-header m-0 h-header-height w-full flex-wrap bg-transparent p-0 text-gray-200 transition-all duration-500 ease-in-out",
        {
          "header--landing__background-transparent shadow-lg": isScrolled,
        },
        className
      )}
    >
      <div className="container mx-auto flex h-full items-center justify-between px-4 sm:px-6 lg:px-8">
        <div className="header__left flex h-full items-center space-x-4">
          <div title="Back to Top">
            <svg
              height={24}
              viewBox=".5 -.2 1023 1024.1"
              width={24}
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              className="cursor-pointer"
              onClick={() => {
                window.scrollTo({
                  behavior: "smooth",
                  top: 0,
                });
              }}
            >
              <path d="m478.5.6c-2.2.2-9.2.9-15.5 1.4-145.3 13.1-281.4 91.5-367.6 212-48 67-78.7 143-90.3 223.5-4.1 28.1-4.6 36.4-4.6 74.5s.5 46.4 4.6 74.5c27.8 192.1 164.5 353.5 349.9 413.3 33.2 10.7 68.2 18 108 22.4 15.5 1.7 82.5 1.7 98 0 68.7-7.6 126.9-24.6 184.3-53.9 8.8-4.5 10.5-5.7 9.3-6.7-.8-.6-38.3-50.9-83.3-111.7l-81.8-110.5-102.5-151.7c-56.4-83.4-102.8-151.6-103.2-151.6-.4-.1-.8 67.3-1 149.6-.3 144.1-.4 149.9-2.2 153.3-2.6 4.9-4.6 6.9-8.8 9.1-3.2 1.6-6 1.9-21.1 1.9h-17.3l-4.6-2.9c-3-1.9-5.2-4.4-6.7-7.3l-2.1-4.5.2-200.5.3-200.6 3.1-3.9c1.6-2.1 5-4.8 7.4-6.1 4.1-2 5.7-2.2 23-2.2 20.4 0 23.8.8 29.1 6.6 1.5 1.6 57 85.2 123.4 185.9s157.2 238.2 201.8 305.7l81 122.7 4.1-2.7c36.3-23.6 74.7-57.2 105.1-92.2 64.7-74.3 106.4-164.9 120.4-261.5 4.1-28.1 4.6-36.4 4.6-74.5s-.5-46.4-4.6-74.5c-27.8-192.1-164.5-353.5-349.9-413.3-32.7-10.6-67.5-17.9-106.5-22.3-9.6-1-75.7-2.1-84-1.3zm209.4 309.4c4.8 2.4 8.7 7 10.1 11.8.8 2.6 1 58.2.8 183.5l-.3 179.8-31.7-48.6-31.8-48.6v-130.7c0-84.5.4-132 1-134.3 1.6-5.6 5.1-10 9.9-12.6 4.1-2.1 5.6-2.3 21.3-2.3 14.8 0 17.4.2 20.7 2z" />
              <path d="m784.3 945.1c-3.5 2.2-4.6 3.7-1.5 2 2.2-1.3 5.8-4 5.2-4.1-.3 0-2 1-3.7 2.1zm-6.9 4.5c-1.8 1.4-1.8 1.5.4.4 1.2-.6 2.2-1.3 2.2-1.5 0-.8-.5-.6-2.6 1.1zm-5 3c-1.8 1.4-1.8 1.5.4.4 1.2-.6 2.2-1.3 2.2-1.5 0-.8-.5-.6-2.6 1.1zm-5 3c-1.8 1.4-1.8 1.5.4.4 1.2-.6 2.2-1.3 2.2-1.5 0-.8-.5-.6-2.6 1.1zm-7.6 4c-3.8 2-3.6 2.8.2.9 1.7-.9 3-1.8 3-2 0-.7-.1-.6-3.2 1.1z" />
            </svg>
          </div>
          <div className="h-4 w-px bg-gray-200"></div>
          <button type="button" className="focus:outline-none">
            <a href="/blog" target="_blank" rel="noopener noreferrer">
              <div className="flex-center whitespace-no-wrap no-underine select-none font-extrabold uppercase focus:outline-none">
                Blog
              </div>
            </a>
          </button>
        </div>
        <div className="header__right flex h-full items-center space-x-4">
          <div className="flex flex-col">
            <ThemeToggle />
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
