// src/components/layout/BackToTop.tsx
"use client";

import { useAtomValue } from "jotai";
import React from "react";
import { FaArrowAltCircleUp } from "react-icons/fa";
import { scrolledStore } from "@/store/theme";

const BackToTopButton = () => {
  const { isScrolled } = useAtomValue(scrolledStore);

  const scrollToTop = () => {
    window.scrollTo({
      behavior: "smooth",
      top: 0,
    });
  };

  if (!isScrolled) {
    return null;
  }

  return (
    <button
      type="button"
      className="fixed bottom-0 right-0 z-10 m-10 size-10 cursor-pointer opacity-20 transition-all duration-300 hover:opacity-75 focus:outline-none"
      title="Scroll To Top"
      onClick={scrollToTop}
    >
      <FaArrowAltCircleUp className="size-10" />
    </button>
  );
};

export default BackToTopButton;

// src/components/layouts/BackToTop.vue
<template>
  <button
    type="button"
    class="fixed right-0 bottom-0 w-10 h-10 cursor-pointer z-10 m-10 hover:opacity-75 focus:outline-none"
    title="Scroll To Top"
    @click="scrollToTop"
  >
    <v-icon name="arrow-up-circle" class="w-10 h-10"></v-icon>
  </button>
</template>

<script>
export default {
  props: {
    isScrolled: {
      type: Boolean,
      default: false
    }
  },
  methods: {
    scrollToTop() {
      window.scrollTo({
        top: 0,
        behavior: "smooth"
      });
    }
  }
};
</script>
