// components/layout/Footer.tsx
import React from "react";
import SocialLinks from "@/components/common/SocialLinks";
import classNames from "classnames";

const Footer = ({
  className,
  children,
  ...props
}: React.ComponentProps<"footer">) => {
  return (
    <footer
      {...props}
      className={classNames(
        "footer surface mt-auto py-4 text-center shadow-box",
        className
      )}
    >
      <div className="container flex items-center justify-between">
        <div className="font-semibold">
          Copyright © {new Date().getFullYear()}
        </div>
        <SocialLinks className="flex-center flex-gap-4 text-2xl" />
      </div>
    </footer>
  );
};

export default Footer;

// src/components/layouts/Footer.vue
<template>
  <footer class="footer text-center py-4 mt-auto surface shadow-box">
    <div class="container flex items-center justify-between">
      <div class="font-semibold">
        Copyright © {{ new Date().getFullYear() }}
      </div>

      <SocialLinks class="flex-center text-2xl gap-2" />
    </div>
  </footer>
</template>

<script>
import SocialLinks from "~/components/common/SocialLinks";

export default {
  components: {
    SocialLinks
  }
};
</script>
