// src/components/blog/NewsFeed.tsx
import React from "react";
import BlogInfo from "@/components/blog/BlogInfo";
import FeedList from "@/components/blog/FeedList";
import { MarkdownPost } from "@/models/markdown.types";

const NewsFeed = ({ posts }: { posts: MarkdownPost[] }) => {
  return (
    <div className="relative mx-auto my-12 flex max-w-xl flex-wrap px-4 sm:px-6 lg:max-w-screen-xl lg:px-8">
      <FeedList posts={posts} />
      <BlogInfo className="mt-8 w-full lg:mt-4 lg:w-1/4" />
    </div>
  );
};

export default NewsFeed;

// src/components/layouts/Newsfeed.vue
<template>
  <div
    class="relative max-w-xl mx-auto px-4 my-12 sm:px-6 lg:px-8 lg:max-w-screen-xl flex flex-wrap"
  >
    <FeedList :page-data="pageData" />
    <BlogInfo class="w-full lg:w-1/4 mt-8 lg:mt-4" />
  </div>
</template>

<script>
import FeedList from "~/components/newsfeed/FeedList";
import BlogInfo from "~/components/widgets/BlogInfo";

export default {
  components: {
    FeedList,
    BlogInfo
  },

  props: {
    pageData: {
      type: Object,
      required: true
    }
  }
};
</script>
