// src/components/Author.vue
<template slot-scope="settings">
  <div class="author flex-center flex-col text-center">
    <g-image
      :alt="settings.siteOwner.name"
      :src="imageUrl"
      class="author__image rounded-full mb-4 shadow-2xl"
      width="180"
      height="180"
      fit="cover"
      blur="10"
    />

    <h1 v-if="showTitle" class="author__site-title text-2xl font-bold mb-4">
      {{ settings.siteOwner.name }}
    </h1>

    <div
      class="author__intro v-html text-left opacity-75"
      v-html="settings.siteOwner.description"
    />
  </div>
</template>

<script>
export default {
  props: {
    showTitle: {
      type: Boolean,
      default: false
    }
  },
  inject: {
    settings: {
      type: Object,
      required: true
    }
  },
  computed: {
    imageUrl() {
      return require(`!!assets-loader?width=150&height=150&fit=cover&blur=10!~/assets/uploads/images/author.jpg`);
    }
  }
};
</script>

// src/components/blog/Author.tsx
import Image from "next/image";
import React from "react";
import { Blog } from "@/constants/meta";
import { getPlaceholderImage } from "@/utils/next-mage";

const AUTHOR_IMAGE = "/uploads/images/author.jpg";

const Author = async () => {
  const authorImage = await getPlaceholderImage(AUTHOR_IMAGE);

  return (
    <div className="author flex-center flex-col text-center">
      <Image
        alt={Blog.METADATA.author}
        src={authorImage.src}
        className="author__image mb-4 rounded-full shadow-lg"
        width={150}
        height={150}
        placeholder="blur"
        blurDataURL={authorImage.placeholder}
      />
      <h1 className="author__site-title mb-4 text-2xl font-bold">
        {Blog.METADATA.author}
      </h1>
      <div className="author__intro text-left italic opacity-75">
        <p>{Blog.METADATA.description}</p>
      </div>
    </div>
  );
};

export default Author;
