// src/components/widgets/BlogInfo.vue
<template>
  <section class="blog-info relative z-10">
    <div
      class="blog-info__content shadow-md p-8 text-on-surface rounded relative"
    >
      <div class="">
        <Author />
        <HorizontalLine class="my-5" />
        <Subscribe />
      </div>
      <CircuitBoard class="absolute inset-0 shadow-md surface z-bg rounded" />
    </div>
  </section>
</template>

<script>
import Author from "~/components/common/Author";
import Subscribe from "~/components/common/Subscribe";
import CircuitBoard from "~/components/common/CircuitBoard";

export default {
  components: {
    Author,
    Subscribe,
    CircuitBoard
  }
};
</script>

<style lang="scss">
.blog-info {
  &__content {
    box-shadow: inset 0px 0px 10px 10px var(--surface);
  }
}
</style>

// src/components/blog/BlogInfo.tsx
import Author from "@/components/blog/Author";
import CircuitBoard from "@/components/blog/CircuitBoard";
import Subscribe from "@/components/blog/Subscribe";
import HorizontalLine from "@/components/common/HorizontalLine";
import classNames from "classnames";
import React from "react";

const BlogInfo = ({ className }: React.ComponentProps<"section">) => {
  return (
    <section className={classNames("blog-info relative text-sm", className)}>
      <div className="blog-info__content text-on-surface sticky rounded-sm px-4 py-8 shadow-md">
        <div className="[&_.author\_\_image--container]:mb-4">
          <Author />
          <div className="my-5">
            <HorizontalLine />
          </div>
        </div>
        <Subscribe />

        <CircuitBoard className="surface z-(--z-bg) absolute inset-0 rounded-sm shadow-md" />
      </div>
    </section>
  );
};

export default BlogInfo;
