// src/components/newsfeed/PostCard.vue
<template>
  <li class="news-feed__list-item pt-8 lg:w-4/5 w-full">
    <PostMeta class="news-feed__list-item__meta" :post="post" />

    <h2
      class="news-feed__list-item__title heading text-3xl sm:text-4xl sm:leading-10 my-4 hover:opacity-75"
    >
      <g-link class="news-feed__list-item__link" :to="post.path">
        {{ post.title }}
      </g-link>
    </h2>

    <figure v-if="post.cover_image">
      <g-link class="news-feed__list-item__link" :to="post.path">
        <g-image
          alt="Cover image"
          class="news-feed__list-item__image shadow-lg mb-4 rounded mt-2"
          :src="coverImage"
          width="1280"
          height="720"
          quality="80"
          fit="cover"
          blur="10"
        />
      </g-link>
      <figcaption></figcaption>
    </figure>

    <p
      class="news-feed__list-item__description v-html mt-3 text-lg leading-7"
      v-html="post.description"
    />

    <PostTags class="news-feed__list-item__tags" :post="post" />
    <hr class="mt-8" />
  </li>
</template>

<script>
import PostMeta from "~/components/common/PostMeta";
import PostTags from "~/components/common/PostTags";

export default {
  components: {
    PostMeta,
    PostTags
  },
  props: {
    post: {
      type: Object,
      required: true
    }
  },
  computed: {
    coverImage() {
      if (!this.post.cover_image) {
        return "";
      }
      return require(`!!assets-loader?width=1280&height=720&fit=cover&blur=10!~/assets${this.post.cover_image}`);
    }
  }
};
</script>

<style lang="scss" scoped>
.news-feed__list-item {
  &__description {
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
}
</style>

// src/components/blog/PostCard.tsx
import React from "react";
import PostMeta from "@/components/blog/PostMeta";
import TagList from "@/components/blog/PostTag";
import { MarkdownPost } from "@/models/markdown.types";

interface PostCardProps {
  post: MarkdownPost;
}

const PostCard: React.FC<PostCardProps> = ({ post }) => {
  const coverImage = post.cover_image ? `${post.cover_image}` : "";

  return (
    <li className="news-feed__list-item w-full pt-8 lg:w-4/5">
      <PostMeta className="news-feed__list-item__meta" post={post} />
      <h2 className="news-feed__list-item__title heading my-4 text-3xl hover:opacity-75 sm:text-4xl sm:leading-10">
        <a
          href={`/blog/posts/${post.slug}`}
          className="news-feed__list-item__link"
        >
          {post.title}
        </a>
      </h2>
      {coverImage && (
        <figure>
          <a
            href={`/blog/posts/${post.slug}`}
            className="news-feed__list-item__link"
          >
            {post.renderCoverImage({
              className:
                "news-feed__list-item__image mb-4 mt-2 rounded shadow-lg",
              height: "720",
              width: "1280",
            })}
          </a>
          <figcaption></figcaption>
        </figure>
      )}
      <p className="news-feed__list-item__description v-html mt-3 text-lg leading-7">
        {post.description}
      </p>
      <TagList className="news-feed__list-item__tags mt-3" post={post} />
      <hr className="-mb-3 mt-6" />
    </li>
  );
};

export default PostCard;
