// legacy/src/components/global/HorizontalLine.vue
<template>
  <div class="horizontal-line w-full mx-0 border-0 h-px" aria-hidden="true" />
</template>

<style lang="scss" scoped>
.horizontal-line {
  background-image: linear-gradient(
    to right,
    transparent 0%,
    var(--primary) 30%,
    var(--primary) 70%,
    transparent 100%
  );
}
</style>

// src/components/common/HorizontalLine.tsx
import classNames from "classnames";
import React from "react";

const HorizontalLine = ({
  className,
  ...props
}: React.ComponentProps<"div">) => {
  return (
    <div
      className={classNames(
        "horizontal-line mx-0 h-px w-full border-0",
        className
      )}
      aria-hidden="true"
      {...props}
    />
  );
};

export default HorizontalLine;
