// src/components/blog/PostMeta.tsx
import classNames from "classnames";
import { format, isValid } from "date-fns";
import React from "react";
import { MarkdownPost } from "@/models/markdown.types";

interface PostDatesProps extends React.ComponentProps<"div"> {
  post: MarkdownPost;
}

const PostMeta = ({ className, post }: PostDatesProps) => {
  const formatDate = (date: Date): string | null => {
    if (!isValid(date)) {
      return null;
    }
    return format(date, "MMMM dd, yyyy");
  };

  const created_at = formatDate(post.created_at);
  const updated_at = post.updated_at ? formatDate(post.updated_at) : null;

  return (
    <div
      className={classNames(
        "text-md font-semibold uppercase tracking-wider text-theme-error opacity-75",
        className
      )}
    >
      <time dateTime={post.created_at.toISOString()}>{created_at}</time>
      {updated_at && (
        <>
          &nbsp;(Updated:&nbsp;
          <time dateTime={post.updated_at?.toISOString()}>{updated_at}</time>)
        </>
      )}
    </div>
  );
};

export default PostMeta;

// src/components/common/PostMeta.vue
<template>
  <div
    class="text-theme-error uppercase font-semibold text-md tracking-wider opacity-75"
  >
    <time :datetime="post.created_at">
      {{ dates.created_at }}
    </time>
    <template v-if="dates.updated_at">
      (Updated:
      <time :datetime="post.updated_at">
        {{ dates.updated_at }}
      </time>
      )
    </template>
  </div>
</template>

<script>
import dayjs from "dayjs";

export default {
  props: {
    post: {
      type: Object,
      required: true
    }
  },

  computed: {
    dates() {
      const formatDate = (rawDate) => {
        if (!dayjs(rawDate).isValid()) {
          return null;
        }
        return dayjs(rawDate).format("MMMM DD, YYYY");
      };
      return {
        created_at: formatDate(this.post.created_at),
        updated_at: formatDate(this.post.updated_at)
      };
    }
  }
};
</script>
